### ISSUE TITLE
When I run the lazybones command with the template it never ask me anything

### ISSUE THREAD

**Issue by GonzaloCalandria** [Adobe-Consulting-Services/lazybones-aem-templates#29]
Hello, I'm trying to follow [this](https://helpx.adobe.com/experience-manager/kt/sites/using/getting-started-wknd-tutorial-develop/part1.html) tutorial and it's using lazybones. My problem is when I run the command lazybones `create aem-multimodule-project 0.0.38 wknd-sites-guide` it never ask me anything... it just create the project with wrong names and that is causing the mvn command gives error at the very beginning.
Am I missing something?

**Comment by justinedelson** [comment]
What is the output of `lazybones --version`?

Do other lazybones templates work correctly? For example `lazybones create nebula-plugin <projectname>` is a template that has similar prompts.

**Comment by GonzaloCalandria** [comment]
The output of `lazybones --version` is `No command '--version'`
It's important to tell that I'm using Windows.
I've never worked with lazybones so I didn't try other templates.

**Comment by justinedelson** [comment]
That sounds like your lazybones installation is corrupt. Unfortunately, I don't know anything about running lazybones on Windows. I'll label this as help wanted to see if anyone else knows what might be causing that. Otherwise, you will probably need to figure out why basic lazybones operations don't work before we can troubleshoot issues with this specific template.

**Comment by GonzaloCalandria** [comment]
Ok, I've figured out that it was a corrupt installation. I've installed again and it worked like a charm.
Thanks @justinedelson with all your help.
